WEBVTT

00:00:01.870 --> 00:00:02.980
Witamy spowrotem.

00:00:03.250 --> 00:00:07.720
Teraz, gdy masz już lekarza, a lekarz jest uruchomiony.

00:00:07.720 --> 00:00:17.710
Przejdźmy do naszego projektu inteligentnego mózgu API, który mam tutaj i zbuduj przykładowy dokument Rafała i używamy tego

00:00:17.710 --> 00:00:24.760
projektu, ponieważ pod koniec tej części będziemy budować plik dokowania dla tego

00:00:24.820 --> 00:00:26.480
całego projektu.

00:00:26.650 --> 00:00:35.670
Zacznijmy od tego, co musimy zrobić, to na samym początku zamknijmy ten serwer.

00:00:35.670 --> 00:00:36.700
Proszę bardzo.

00:00:36.820 --> 00:00:45.810
Musimy najpierw skompilować obraz, który można odczytać, a także sposób, w jaki to robimy, tworząc nowy

00:00:45.840 --> 00:00:50.030
plik w katalogu głównym naszego projektu.

00:00:50.070 --> 00:00:53.430
Powiem więc, że zamierzam to zrobić tutaj.

00:00:53.450 --> 00:01:02.190
Powiem "dotknij" i będziemy musieli zadzwonić do tego pliku dokera, a ten plik Daka będzie naszym obrazem.

00:01:02.270 --> 00:01:08.570
Więc jeśli uderzę w Enter Here, zobaczymy, że mamy już plik doc w naszym projekcie.

00:01:08.570 --> 00:01:14.020
Otwórzmy to, a teraz jest całkowicie pusto i to jest w porządku.

00:01:14.120 --> 00:01:21.560
Teraz, jeśli pamiętasz, możemy dołączyć obrazy, które pokazałem ci w środku lub w centrum, w którym byli inni

00:01:21.560 --> 00:01:22.210
ludzie.

00:01:22.490 --> 00:01:27.830
Na przykład chcemy, aby węzeł działał na tym projekcie.

00:01:27.830 --> 00:01:30.840
Zobaczmy wersję naszego węzła dla naszego inteligentnego mózgu.

00:01:30.890 --> 00:01:35.270
Jeśli nie zapłacę żadnej opłaty, widzę, że jest to punkt dziewięć punktów jeden.

00:01:35.270 --> 00:01:38.740
Dobra, chodźmy do Dr. Haab, które mam tutaj.

00:01:38.840 --> 00:01:41.090
I sprawdźmy węzeł i

00:01:44.710 --> 00:01:54.010
chcemy uruchomić wersję, którą widzimy, która ma wiodącą wersję najnowszej wersji 8, co jest dla nas dobre.

00:01:54.010 --> 00:01:55.670
Jest również nazywany węglem.

00:01:55.690 --> 00:01:59.010
Więc jeśli kliknę tutaj, to widzę.

00:01:59.010 --> 00:02:05.030
O tak, to plik dokera, ale potrzebuję węzła lub węzła.

00:02:05.240 --> 00:02:14.360
Ta konkretna wersja na razie możemy po prostu powiedzieć z wielkimi literami, a my po prostu

00:02:14.360 --> 00:02:18.370
dodamy węgiel węzła i to wszystko.

00:02:18.370 --> 00:02:23.080
Mówimy więc, że po prostu pobieramy obraz węglowy węzła

00:02:25.960 --> 00:02:34.410
i mogę umieścić tutaj numer wersji i dowolne z tych znaczników, które widzisz, które chcesz dla swojego projektu.

00:02:34.510 --> 00:02:41.110
I wreszcie mam zamiar wykonać polecenie noszące nazwę CMT, które oznacza polecenie, a

00:02:41.110 --> 00:02:47.590
tutaj będzie to zestaw poleceń, które chcemy uruchomić po pobraniu wersji węzła.

00:02:47.600 --> 00:02:54.960
Więc wszystko, co powiem, to Ben Bash, a pokażę ci, co to zrobi w ciągu sekundy.

00:02:54.980 --> 00:03:03.290
Teraz pierwsze polecenie, jak już powiedziałem, mówi dokownikowi, aby ponownie używał obrazu węzła z lub koncentratora oficjalnego

00:03:03.290 --> 00:03:05.240
repozytorium obrazów Daquiri.

00:03:05.570 --> 00:03:10.250
I to właśnie nazywamy rodzicielskim wizerunkiem naszego wizerunku.

00:03:10.250 --> 00:03:19.410
Teraz CMD lub instrukcja polecenia mówi nam, co należy uruchomić w kontenerze, co pozwala nam ponownie uzyskać dostęp do jego profilu

00:03:19.680 --> 00:03:24.160
bash, a coś, co zamierzam ci pokazać, nabierze więcej sensu.

00:03:24.180 --> 00:03:32.120
Teraz przejdźmy do naszego terminalu, upewnijmy się, że zapisujemy ten plik i mogę teraz uruchomić ponownie okno dokowane poleceń,

00:03:32.220 --> 00:03:35.680
które pochodzi z instalacją dokera, którą właśnie mieliśmy.

00:03:36.360 --> 00:03:41.000
Mówimy tylko o budowaniu dockera i nadaj mu nazwę znacznika.

00:03:41.070 --> 00:03:46.620
Więc Dasht T jest dla tagu i możemy powiedzieć, co chcesz, powiemy.

00:03:46.620 --> 00:03:51.800
Super niesamowity pojemnik.

00:03:51.910 --> 00:03:59.390
A kiedy już wciskam enter i tutaj jest trochę sztuczki, ponieważ musimy powiedzieć, co zbudować.

00:03:59.420 --> 00:04:03.710
Musimy nadać mu czas na końcu, więc zbuduj wszystko.

00:04:03.830 --> 00:04:09.800
A obecny katalog znajdzie dokument lub plik i gotowe.

00:04:10.260 --> 00:04:13.710
Działa wszystko uruchamiając wszystko, co tu widzisz.

00:04:13.830 --> 00:04:16.710
Robi węgiel uwaga From.

00:04:16.720 --> 00:04:20.750
Krok 2 polecenie, które właśnie powiedzieliśmy.

00:04:20.970 --> 00:04:27.990
I mówi, że udało się zbudować i skutecznie oznakować super niesamowity pojemnik.

00:04:28.060 --> 00:04:35.230
To właśnie stworzyło nasz pierwszy obraz Daquiri z nazwą tagu przy użyciu ciemnego profilu, który właśnie

00:04:35.620 --> 00:04:36.160
mieliśmy.

00:04:36.190 --> 00:04:42.410
I znowu uruchomiłem to polecenie z katalogu głównego, w którym znajduje się nasz plik doc.

00:04:45.020 --> 00:04:46.670
Teraz zajęło to trochę czasu.

00:04:46.790 --> 00:04:55.010
Jeśli ponownie uruchomię to polecenie, zobacz, o ile jest to szybsze, a to dlatego, że zamiast pobierać

00:04:55.100 --> 00:05:02.240
Noada od nowa, tak jak podczas pierwszego korzystania z buforowanego obrazu lub zapamiętania

00:05:02.240 --> 00:05:02.790
obrazu.

00:05:02.930 --> 00:05:05.290
Więc staje się o wiele szybszy.

00:05:05.450 --> 00:05:09.770
A teraz pozwól mi wyjaśnić, że możemy zrobić coś zabawnego.

00:05:09.860 --> 00:05:17.380
Możemy zrobić zamiast Dr. Rachunek, który właśnie zrobiliśmy, robimy doktorowi biegnij i biegnij Daco.

00:05:17.390 --> 00:05:20.400
Musimy dać jej kilka parametrów.

00:05:20.960 --> 00:05:22.370
A potem nazwa naszego kontenera.

00:05:22.370 --> 00:05:32.460
Powiedzmy, że super OSS może zająć się tworzeniem Whoa.

00:05:32.600 --> 00:05:33.540
Po prostu to widzisz.

00:05:34.370 --> 00:05:41.490
Właśnie uruchomiliśmy nasz kontener do dokowania i zabraliśmy nas do naszego kontenera.

00:05:41.490 --> 00:05:44.000
Teraz widzisz, że mój terminal jest zupełnie inny.

00:05:44.010 --> 00:05:46.160
Jesteśmy w kontenerze.

00:05:48.360 --> 00:05:50.000
Dlaczego to zrobił?

00:05:50.040 --> 00:05:53.280
Ponieważ właśnie uruchomiliśmy nasz kontener dokowania.

00:05:53.580 --> 00:06:03.580
A jeśli pamiętasz, nasze polecenie brzmiało: bin bash, a ten komentarz mówi po prostu, aby przejść do profilu bash, który

00:06:03.760 --> 00:06:11.000
jest bashiem Ben naszego kontenera i widzisz tutaj, że mamy root na jakimś haszyszu.

00:06:11.080 --> 00:06:17.570
Jest to mieszanie generowane losowo przez ciemniejsze, aby wiedzieć, które pojemniki.

00:06:17.620 --> 00:06:18.450
Bardzo fajny.

00:06:18.610 --> 00:06:24.710
Ale jeśli faktycznie zainstalujemy węzeł, powinniśmy mieć możliwość prawidłowego polecenia nuty.

00:06:24.760 --> 00:06:27.410
Tak więc, nie wylewajmy fibryny V z naszego pojemnika.

00:06:28.990 --> 00:06:33.950
Spójrz, że mamy wersję węzła, ale widzę, że mam sześć punktów czternaście punkt jeden.

00:06:34.510 --> 00:06:42.500
Nie tego się spodziewaliśmy, ponieważ jeśli spojrzymy tutaj, zainstalowaliśmy węgiel i to powinno być punktem w miłości.

00:06:42.520 --> 00:06:47.320
Ale zamiast tego dostaliśmy sześć punktów czternaście, które są borem.

00:06:47.410 --> 00:06:48.080
Ciekawy.

00:06:48.100 --> 00:06:52.620
Zmień numer wersji na rzeczywistą liczbę.

00:06:52.630 --> 00:06:58.280
Więc w naszym przypadku Leisure mówi, że mamy jedną wersję osiem punkt jedenasta punkt końcowy.

00:06:58.300 --> 00:06:59.400
Zobaczmy, co tu mamy.

00:06:59.410 --> 00:07:02.190
Punkt jeden chce to zapisać.

00:07:02.370 --> 00:07:09.330
I mam zamiar wyjść, jeśli po prostu wpisujesz wyjście i ponownie uruchamiasz nasze polecenia, aby pamiętać, że pierwszą rzeczą, którą

00:07:09.330 --> 00:07:12.780
robimy, jest zbudowanie i zobaczmy, co się tutaj stanie.

00:07:16.740 --> 00:07:17.190
W porządku.

00:07:17.190 --> 00:07:18.730
To wszystko buduje.

00:07:19.170 --> 00:07:22.650
A teraz, jeśli uruchomimy naszą drugą komendę, którą

00:07:25.670 --> 00:07:28.510
uruchomi Daka i zobaczmy wersję węzła.

00:07:28.940 --> 00:07:32.080
W porządku, mamy poprawną wersję naszego węzła.

00:07:33.090 --> 00:07:37.890
Zawsze chcesz to sprawdzić, aby upewnić się, że wszystko, co zainstalowałeś, jest poprawne, ponieważ czasami możesz

00:07:37.890 --> 00:07:41.460
popełniać błędy i sądzić, że masz wersję CRN, ale nie masz.

00:07:41.460 --> 00:07:48.000
Zawsze więc chcesz sprawdzić swoje pojemniki, aby upewnić się, że wszystko, co masz skonfigurowane, faktycznie tam

00:07:48.000 --> 00:07:48.660
jest.

00:07:48.800 --> 00:07:51.670
Ale jak widać wszystko działa płynnie.

00:07:51.690 --> 00:07:56.820
Mamy maszynę kontener z presetem węzła lub dla nas.

00:07:57.070 --> 00:07:59.670
I jak proste jest to.

00:08:00.000 --> 00:08:03.090
Przy okazji tylko dla zabawy, pozwól mi wyjść z tego ponownie.

00:08:03.610 --> 00:08:07.750
Chcę wyczyścić i uruchomić to polecenie

00:08:10.260 --> 00:08:19.360
bez parametrów I-T myślnika i widzisz, że możemy wejść do kontenera, a to dlatego, że

00:08:20.080 --> 00:08:29.830
polecenie daje nam to, co nazywamy środowiskiem TDY lub pozwala nam wejść do tego doku lub kontenera.

00:08:29.890 --> 00:08:34.380
Teraz, kiedy trochę się przyzwyczailiśmy do dokowania, musimy się jeszcze trochę nauczyć, więc zobaczę cię

00:08:34.390 --> 00:08:35.670
w następnym filmie.

00:08:35.870 --> 00:08:36.120
Buh-Bye.