WEBVTT

00:00:01.870 --> 00:00:02.980
Bine ai revenit.

00:00:03.250 --> 00:00:07.720
Acum că aveți un medic înființat și medicul se execută.

00:00:07.720 --> 00:00:17.710
Să mergem la proiectul nostru inteligent API pe care îl am aici și să construiesc un exemplu de doc Rafal și

00:00:17.710 --> 00:00:24.760
folosim acest proiect, deoarece până la sfârșitul acestei secțiuni vom construi un fișier de docare

00:00:24.820 --> 00:00:26.480
pentru întregul proiect.

00:00:26.650 --> 00:00:35.670
Deci, pentru a începe ceea ce trebuie să facem este bine să în primul rând să închidem acest server deocamdată.

00:00:35.670 --> 00:00:36.700
Acolo te duci.

00:00:36.820 --> 00:00:45.810
Și ceea ce trebuie să facem este să construim mai întâi o imagine pe care o poate citi sau să o citim și modul în care

00:00:45.840 --> 00:00:50.030
facem acest lucru este crearea unui nou fișier la baza proiectului nostru.

00:00:50.070 --> 00:00:53.430
Așa că am de gând să spun că o să fac aici.

00:00:53.450 --> 00:01:02.190
Voi spune o atingere și trebuie să sunăm acest fișier docer și acest fișier Daka va fi imaginea noastră.

00:01:02.270 --> 00:01:08.570
Deci, dacă l-am lovit pe Enter, vedem că acum avem un fișier doc în proiectul nostru.

00:01:08.570 --> 00:01:14.020
Deci, să deschidem acest lucru și acest lucru este complet gol acum și este bine.

00:01:14.120 --> 00:01:21.560
Acum, dacă vă amintiți, putem include imaginile pe care le-am arătat sau pe care le-au arătat și alte

00:01:21.560 --> 00:01:22.210
persoane.

00:01:22.490 --> 00:01:27.830
De exemplu, dorim ca nodul să fie difuzat pe acest proiect.

00:01:27.830 --> 00:01:30.840
Să vedem versiunea nodului nostru pentru creierul nostru inteligent.

00:01:30.890 --> 00:01:35.270
Dacă nu fac nicio taxă, văd că este un punct nou nou.

00:01:35.270 --> 00:01:38.740
Bine, să mergem la Dr. Haab pe care o am aici.

00:01:38.840 --> 00:01:41.090
Și să verificăm nodul și

00:01:44.710 --> 00:01:53.530
vrem să executăm o versiune pe care o vedem care are conducerea ultimei versiuni a versiunii 8, care este bine pentru

00:01:53.530 --> 00:01:54.010
noi.

00:01:54.010 --> 00:01:55.670
Se numește și carbon.

00:01:55.690 --> 00:01:59.010
Deci dacă fac clic aici văd asta.

00:01:59.010 --> 00:02:05.030
Da, asta e un dosar de docare, dar am nevoie doar de carbonul nodului sau de nodul.

00:02:05.240 --> 00:02:14.360
Această versiune specifică de acum putem spune cu litere mari și vom merge mai departe și vom spune

00:02:14.360 --> 00:02:18.370
un carbon de nod și asta-i tot.

00:02:18.370 --> 00:02:23.080
Deci, spunem doar să luăm imaginea carbonului din nod și

00:02:25.960 --> 00:02:34.410
pot pune aici numărul versiunii și oricare dintre aceste etichete pe care le vedeți că doriți pentru proiectul dvs.

00:02:34.510 --> 00:02:41.110
Și apoi, în sfârșit, o să fac o comandă notter numită CMT, care vine de la comandă și aici

00:02:41.110 --> 00:02:47.590
va fi o serie de comenzi pe care vrem să le executăm după ce vom lua versiunea nodului.

00:02:47.600 --> 00:02:54.960
Tot ce am de gând să spun este Ben Bash și vă voi arăta ce se întâmplă într-o secundă.

00:02:54.980 --> 00:03:03.290
Acum, prima comandă pe care am spus-o mai înainte îi spune dockerului să folosească imaginea nodului din hub sau din nou hub-ul

00:03:03.290 --> 00:03:05.240
repozitoriu oficial de imagine daquiri.

00:03:05.570 --> 00:03:10.250
Și aceasta este ceea ce numim o imagine părintească a imaginii noastre.

00:03:10.250 --> 00:03:19.410
Acum, CMD sau instrucțiunea de comandă ne spune ce să fugim în container, ceea ce ne permite să accesăm din nou profilul său de bash ceva ce

00:03:19.680 --> 00:03:24.160
am să vă arăt că veți avea mai mult sens mai târziu.

00:03:24.180 --> 00:03:32.120
Acum, hai să mergem la terminalul nostru, asigurându-ne că salvăm acest fișier și pot rula din nou comanda de andocare a comenzii care

00:03:32.220 --> 00:03:35.680
vine cu instalarea doc-ului pe care tocmai am avut-o.

00:03:36.360 --> 00:03:41.000
Spunem doar construirea unui docker și dați-i un nume de etichetă.

00:03:41.070 --> 00:03:46.620
Deci Dasht T este pentru etichetă și putem spune ce vrei tu vom spune.

00:03:46.620 --> 00:03:51.800
Container super minunat.

00:03:51.910 --> 00:03:59.390
Și odată ce apăs pe Enter și iată un mic truc pentru că trebuie să-i spunem ce să construim.

00:03:59.420 --> 00:04:03.710
Trebuie să-i dăm o perioadă la sfârșit, astfel încât să construim totul.

00:04:03.830 --> 00:04:09.800
Și directorul curent va găsi un doc sau un fișier și acolo te duci.

00:04:10.260 --> 00:04:13.710
Rulează tot ce rulează tot ce vezi aici.

00:04:13.830 --> 00:04:16.710
Face cartea De la nota.

00:04:16.720 --> 00:04:20.750
Pasul 2 comanda pe care tocmai am spus-o.

00:04:20.970 --> 00:04:27.990
Și spune că a construit cu succes și a etichetat cu succes containerul super minunat.

00:04:28.060 --> 00:04:35.230
Asta a creat prima noastră imagine cu daquiri cu numele etichetei folosind profilul întunecat pe care l-am avut în

00:04:35.620 --> 00:04:36.160
prezent.

00:04:36.190 --> 00:04:42.410
Și din nou am rulat această comandă din directorul rădăcină, unde se află fișierul doc.

00:04:45.020 --> 00:04:46.670
Acum a fost nevoie de ceva timp.

00:04:46.790 --> 00:04:55.010
Dacă am executat această comandă, văd din nou cât de repede a fost asta și asta pentru că în loc să descarce Noad peste tot

00:04:55.100 --> 00:05:02.240
din nou, așa cum a făcut prima oară în jurul Dockerilor, care va folosi imaginea memorată în cache sau își amintește

00:05:02.240 --> 00:05:02.790
imaginea.

00:05:02.930 --> 00:05:05.290
Deci devine mult mai rapid.

00:05:05.450 --> 00:05:09.770
Și acum permiteți-mi să clar că putem face ceva distractiv.

00:05:09.860 --> 00:05:17.380
Putem face în loc de Dr. Bill acum pe care tocmai l-am făcut dr. alerga și conduce Daco.

00:05:17.390 --> 00:05:20.400
Trebuie să îi oferim câțiva parametri.

00:05:20.960 --> 00:05:22.370
Și apoi numele containerului nostru.

00:05:22.370 --> 00:05:29.170
Deci, să spunem că super OSS poate avea grijă că am creat

00:05:31.890 --> 00:05:32.460
Whoa.

00:05:32.600 --> 00:05:33.540
Vedeți doar asta.

00:05:34.370 --> 00:05:41.490
Tocmai am fugit containerul de andocare și ne-a dus la containerul nostru.

00:05:41.490 --> 00:05:44.000
Acum vedeți că terminalul meu este complet diferit.

00:05:44.010 --> 00:05:46.160
Suntem în interiorul containerului.

00:05:48.360 --> 00:05:50.000
De ce a făcut asta?

00:05:50.040 --> 00:05:53.280
Pentru că tocmai am fugit containerul nostru de docare.

00:05:53.580 --> 00:06:03.580
Și dacă vă amintiți comanda noastră a fost de a face bin bash și acest comentariu pur și simplu spune să intrăm în profilul bash

00:06:03.760 --> 00:06:11.000
care este bash bas de container nostru și veți vedea aici că avem rădăcină la unele hash.

00:06:11.080 --> 00:06:17.570
Acesta este un hash generat la întâmplare de mai întunecat pentru a ști care containere care.

00:06:17.620 --> 00:06:18.450
Foarte tare.

00:06:18.610 --> 00:06:24.710
Dar dacă am instalat de fapt nod, atunci ar trebui să fim capabili să avem corect comanda note.

00:06:24.760 --> 00:06:27.410
Deci, fibrina nu are linie V din containerul nostru.

00:06:28.990 --> 00:06:33.950
Uită-te la faptul că avem versiunea nodului, dar văd că am șase puncte paisprezece punct unu.

00:06:34.510 --> 00:06:42.500
Asta nu ne-am așteptat, pentru că dacă privim aici, am instalat carbon și acesta ar trebui să fie un punct în dragoste.

00:06:42.520 --> 00:06:47.320
În schimb, avem șase puncte paisprezece, ceea ce înseamnă bor.

00:06:47.410 --> 00:06:48.080
Interesant.

00:06:48.100 --> 00:06:52.620
Să schimbăm numărul versiunii la numărul real.

00:06:52.630 --> 00:06:58.280
Deci, în cazul nostru, Leisure spune că noi o versiune opt punct unsprezece un punct final.

00:06:58.300 --> 00:06:59.400
Să vedem ce avem aici.

00:06:59.410 --> 00:07:02.190
Punctul unu vrea să salveze acest lucru.

00:07:02.370 --> 00:07:09.330
Și voi ieși afară dacă doar tastați ieșirea și reluați din nou comenzile noastre pentru a vă aminti că primul lucru pe care îl

00:07:09.330 --> 00:07:12.780
facem este să construim și să vedem ce se întâmplă aici.

00:07:16.740 --> 00:07:17.190
In regula.

00:07:17.190 --> 00:07:18.730
Construiește totul.

00:07:19.170 --> 00:07:22.650
Și acum, dacă ne conducem cealaltă comandă care este

00:07:25.670 --> 00:07:28.510
Daka și să vedem versiunea nodului.

00:07:28.940 --> 00:07:32.080
În regulă avem versiunea nodului corectă.

00:07:33.090 --> 00:07:37.890
Întotdeauna doriți să verificați acest lucru pentru a vă asigura că tot ce ați instalat este corect deoarece, uneori,

00:07:37.890 --> 00:07:41.460
puteți face greșeli și credeți că aveți o versiune CRN, dar nu o faceți.

00:07:41.460 --> 00:07:48.000
Deci, întotdeauna doriți să vă verificați recipientele pentru a vă asigura că ceea ce ați configurat este de fapt

00:07:48.000 --> 00:07:48.660
acolo.

00:07:48.800 --> 00:07:51.670
Dar, după cum puteți vedea, totul se desfășoară fără probleme.

00:07:51.690 --> 00:07:56.820
Avem o mașină un container cu nod presetat sau pentru noi.

00:07:57.070 --> 00:07:59.670
Și cât de simplu este asta.

00:08:00.000 --> 00:08:03.090
Apropo pentru distracție, lasă-mă să iasă din asta din nou.

00:08:03.610 --> 00:08:07.750
Vreau să clar și să execut această

00:08:10.260 --> 00:08:19.360
comandă fără parametrii I-T și văd că putem intra în container și asta pentru că comanda

00:08:20.080 --> 00:08:29.830
ne dă ceea ce numim un mediu TDY sau ne permite să intrăm în docul respectiv în container.

00:08:29.890 --> 00:08:34.380
Acum, când ne-am obișnuit puțin, avem mai multe lucruri de învățat, așa că te voi

00:08:34.390 --> 00:08:35.670
vedea în următorul videoclip.

00:08:35.870 --> 00:08:36.120
Buh-Pa.