WEBVTT

00:00:01.870 --> 00:00:02.980
Selamat datang kembali.

00:00:03.250 --> 00:00:07.720
Sekarang Anda sudah menyiapkan dokter dan dokter sedang menjalankan.

00:00:07.720 --> 00:00:17.710
Mari kita pergi ke proyek API otak pintar kita yang saya miliki di sini dan membangun sampel dokumen Rafal dan kita menggunakan

00:00:17.710 --> 00:00:24.760
proyek ini karena pada akhir bagian ini kita benar-benar akan membangun file buruh pelabuhan untuk

00:00:24.820 --> 00:00:26.480
seluruh proyek ini.

00:00:26.650 --> 00:00:35.670
Jadi untuk memulai apa yang perlu kita lakukan adalah untuk pertama-tama mari kita tutup server ini sekarang.

00:00:35.670 --> 00:00:36.700
Ini dia.

00:00:36.820 --> 00:00:45.810
Dan apa yang perlu kita lakukan adalah pertama membangun gambar file gambar yang atau dapat dibaca dan cara kita melakukannya

00:00:45.840 --> 00:00:50.030
adalah dengan membuat file baru di root proyek kami.

00:00:50.070 --> 00:00:53.430
Jadi saya akan mengatakan sebenarnya saya hanya akan melakukannya di sini.

00:00:53.450 --> 00:01:02.190
Saya akan mengatakan sentuhan dan kita harus memanggil file buruh pelabuhan ini dan file Daka ini akan menjadi gambar kita.

00:01:02.270 --> 00:01:08.570
Jadi jika saya menekan Enter Here kita melihat bahwa kita sekarang memiliki file doc di proyek kami.

00:01:08.570 --> 00:01:14.020
Jadi mari kita buka ini dan ini benar-benar kosong sekarang dan tidak apa-apa.

00:01:14.120 --> 00:01:21.560
Sekarang di sini, jika Anda ingat, kami dapat menyertakan gambar yang saya tunjukkan di atau hub orang

00:01:21.560 --> 00:01:22.210
lain.

00:01:22.490 --> 00:01:27.830
Jadi misalnya kita ingin simpul untuk dijalankan pada proyek ini.

00:01:27.830 --> 00:01:30.840
Mari kita lihat versi node kami untuk otak cerdas kita.

00:01:30.890 --> 00:01:35.270
Jika saya tidak melakukan biaya garis, saya melihat bahwa itu adalah poin sembilan poin satu.

00:01:35.270 --> 00:01:38.740
Baiklah mari kita pergi ke Dr. Haab yang saya miliki di sini.

00:01:38.840 --> 00:01:41.090
Dan mari kita periksa

00:01:44.710 --> 00:01:54.010
node dan kami ingin menjalankan versi yang kami lihat yang memimpin versi terbaru dari versi 8 yang baik untuk kita.

00:01:54.010 --> 00:01:55.670
Ini juga disebut karbon.

00:01:55.690 --> 00:01:59.010
Jadi jika saya klik di sini saya melihat itu.

00:01:59.010 --> 00:02:05.030
Oh ya itu file buruh pelabuhan tapi saya hanya perlu simpul karbon atau simpul.

00:02:05.240 --> 00:02:14.360
Versi spesifik ini untuk saat ini kita hanya dapat mengatakan dengan huruf kapital dan kita akan langsung melanjutkan

00:02:14.360 --> 00:02:18.370
dan mengatakan simpul karbon dan hanya itu.

00:02:18.370 --> 00:02:23.080
Jadi kami katakan, ambil saja node carbon image dan

00:02:25.960 --> 00:02:34.410
saya bisa letakkan di sini nomor versi dan semua tag ini yang Anda lihat diinginkan untuk proyek Anda.

00:02:34.510 --> 00:02:41.110
Dan akhirnya saya akan melakukan perintah nother bernama CMT yang merupakan singkatan dari perintah dan di

00:02:41.110 --> 00:02:47.590
sini akan menjadi array perintah yang ingin kita jalankan setelah kita ambil versi node

00:02:47.600 --> 00:02:54.960
Jadi yang akan saya katakan adalah Ben Bash dan saya akan menunjukkan kepada Anda apa yang dilakukannya dalam sedetik.

00:02:54.980 --> 00:03:03.290
Sekarang perintah pertama seperti yang saya katakan sebelumnya memberitahu buruh pelabuhan untuk menggunakan gambar node dari atau hub lagi

00:03:03.290 --> 00:03:05.240
repositori gambar daquiri resmi.

00:03:05.570 --> 00:03:10.250
Dan inilah yang kita sebut gambar induk dari gambar kita.

00:03:10.250 --> 00:03:19.410
Sekarang CMD atau instruksi perintah memberi tahu kita apa yang harus dijalankan dalam wadah yang memungkinkan kita untuk mengakses profil bashnya lagi sesuatu

00:03:19.680 --> 00:03:24.160
yang akan saya tunjukkan kepada Anda akan lebih masuk akal nanti.

00:03:24.180 --> 00:03:32.120
Sekarang mari kita pergi ke terminal kita pastikan kita menyimpan file ini dan saya dapat menjalankan sekarang perintah docker lagi yang

00:03:32.220 --> 00:03:35.680
datang dengan menginstal docker yang baru saja kita miliki.

00:03:36.360 --> 00:03:41.000
Kami hanya mengatakan buruh pelabuhan membangun dan memberikannya nama tag.

00:03:41.070 --> 00:03:46.620
Jadi Dasht T adalah untuk tag dan kami dapat mengatakan apa pun yang Anda inginkan, kami akan katakan.

00:03:46.620 --> 00:03:51.800
Wadah super mengagumkan.

00:03:51.910 --> 00:03:59.390
Dan begitu saya menekan enter dan inilah sedikit trik karena kita harus mengatakannya apa yang harus dibangun.

00:03:59.420 --> 00:04:03.710
Kita harus memberikannya periode di akhir jadi bangun semua.

00:04:03.830 --> 00:04:09.800
Dan direktori saat ini akan menemukan dokumen atau file dan di sana Anda pergi.

00:04:10.260 --> 00:04:13.710
Ini menjalankan semua yang menjalankan semua yang Anda lihat di sini.

00:04:13.830 --> 00:04:16.710
Itu melakukan karbon catatan.

00:04:16.720 --> 00:04:20.750
Langkah 2 perintah yang baru saja kita katakan.

00:04:20.970 --> 00:04:27.990
Dan dikatakan berhasil membangun dan berhasil menandai wadah yang sangat luar biasa.

00:04:28.060 --> 00:04:35.230
Ini baru saja membuat gambar daquiri pertama kami dengan nama tag menggunakan profil gelap yang baru saja kami

00:04:35.620 --> 00:04:36.160
miliki.

00:04:36.190 --> 00:04:42.410
Dan lagi saya menjalankan perintah ini dari direktori root yang merupakan tempat file doc kami berada.

00:04:45.020 --> 00:04:46.670
Sekarang butuh sedikit waktu.

00:04:46.790 --> 00:04:55.010
Jika saya telah menjalankan perintah ini lagi, lihat seberapa cepat itu dan itu karena alih-alih mengunduh Noad lagi

00:04:55.100 --> 00:05:02.240
seperti yang dilakukan pertama kali di Dockers akan menggunakan gambar yang di-cache atau mengingat

00:05:02.240 --> 00:05:02.790
gambar.

00:05:02.930 --> 00:05:05.290
Jadi itu menjadi jauh lebih cepat.

00:05:05.450 --> 00:05:09.770
Dan sekarang saya jelaskan ini kita bisa melakukan sesuatu yang menyenangkan.

00:05:09.860 --> 00:05:17.380
Kita bisa melakukan alih-alih Dr. Bill sekarang yang baru saja kita lakukan kita lakukan Dr. lari dan lari Daco.

00:05:17.390 --> 00:05:20.400
Kami harus memberikan beberapa parameter.

00:05:20.960 --> 00:05:22.370
Dan kemudian nama wadah kami.

00:05:22.370 --> 00:05:32.460
Jadi misalkan OSS super dapat menjaga bahwa kami menciptakan Whoa.

00:05:32.600 --> 00:05:33.540
Apakah Anda baru saja melihatnya?

00:05:34.370 --> 00:05:41.490
Kami baru saja berlari wadah docking kami dan itu membawa kami ke wadah kami.

00:05:41.490 --> 00:05:44.000
Sekarang Anda melihat bahwa terminal saya sangat berbeda.

00:05:44.010 --> 00:05:46.160
Kami berada di dalam wadah.

00:05:48.360 --> 00:05:50.000
Sekarang mengapa itu melakukan itu.

00:05:50.040 --> 00:05:53.280
Karena kami baru saja menjalankan wadah buruh pelabuhan kami.

00:05:53.580 --> 00:06:03.580
Dan jika Anda ingat perintah kami adalah melakukan bin bash dan komentar ini hanya mengatakan untuk masuk ke profil bash yang merupakan bash

00:06:03.760 --> 00:06:11.000
Ben dari wadah kami dan Anda lihat di sini bahwa kami memiliki root di beberapa hash.

00:06:11.080 --> 00:06:17.570
Ini adalah hash yang dihasilkan secara acak oleh lebih gelap untuk mengetahui wadah mana.

00:06:17.620 --> 00:06:18.450
Sangat keren.

00:06:18.610 --> 00:06:24.710
Tetapi jika kita benar-benar menginstal node maka kita harus dapat memiliki perintah note dengan benar.

00:06:24.760 --> 00:06:27.410
Jadi fibrin no dash V dari wadah kami.

00:06:28.990 --> 00:06:33.950
Lihatlah bahwa kita memiliki versi simpul tetapi saya melihat saya mendapat enam koma empat koma satu.

00:06:34.510 --> 00:06:42.500
Bukan itu yang kami harapkan karena jika kami melihat ke sini kami memasang karbon dan itu seharusnya menjadi titik cinta.

00:06:42.520 --> 00:06:47.320
Tetapi sebaliknya kita mendapat enam koma empat belas yang merupakan boron.

00:06:47.410 --> 00:06:48.080
Menarik.

00:06:48.100 --> 00:06:52.620
Mari kita ubah nomor versi ke nomor yang sebenarnya.

00:06:52.630 --> 00:06:58.280
Jadi dalam kasus kami, Leisure mengatakan bahwa kami satu versi delapan koma sebelas titik akhir.

00:06:58.300 --> 00:06:59.400
Mari kita lihat apa yang kita miliki di sini.

00:06:59.410 --> 00:07:02.190
Poin satu ingin menyimpan ini.

00:07:02.370 --> 00:07:09.330
Dan saya akan keluar jika Anda hanya mengetik keluar dan menjalankan kembali perintah kami untuk mengingat hal pertama yang kami lakukan adalah kami

00:07:09.330 --> 00:07:12.780
ingin membangun dan mari kita lihat apa yang terjadi di sini.

00:07:16.740 --> 00:07:17.190
Baiklah.

00:07:17.190 --> 00:07:18.730
Itu membangun segalanya.

00:07:19.170 --> 00:07:22.650
Dan sekarang jika kita menjalankan perintah kita yang lain yaitu

00:07:25.670 --> 00:07:28.510
Daka run dan mari kita lihat versi node.

00:07:28.940 --> 00:07:32.080
Baiklah, kita memiliki versi simpul yang benar.

00:07:33.090 --> 00:07:37.890
Anda selalu ingin memeriksa ini untuk memastikan apa pun yang Anda instal sudah benar karena kadang-kadang Anda

00:07:37.890 --> 00:07:41.460
dapat membuat kesalahan dan berpikir Anda memiliki versi CRN tetapi tidak.

00:07:41.460 --> 00:07:48.000
Jadi, Anda selalu ingin memeriksa wadah Anda untuk memastikan bahwa apa pun yang telah Anda siapkan benar-benar ada di

00:07:48.000 --> 00:07:48.660
sana.

00:07:48.800 --> 00:07:51.670
Tapi seperti yang Anda lihat semuanya berjalan lancar.

00:07:51.690 --> 00:07:56.820
Kami memiliki mesin wadah dengan simpul yang telah ditetapkan atau untuk kami.

00:07:57.070 --> 00:07:59.670
Dan betapa sederhananya itu.

00:08:00.000 --> 00:08:03.090
Ngomong-ngomong hanya untuk bersenang-senang biarkan aku keluar dari ini lagi.

00:08:03.610 --> 00:08:07.750
Saya ingin menghapus dan mari kita jalankan

00:08:10.260 --> 00:08:19.360
perintah ini tanpa parameter I-T dasbor dan Anda melihat bahwa kita bisa masuk ke wadah dan itu karena

00:08:20.080 --> 00:08:29.830
perintah memberi kita apa yang kita sebut lingkungan TDY atau memungkinkan kita untuk masuk ke dermaga atau wadah ini.

00:08:29.890 --> 00:08:34.380
Sekarang setelah kami menjadi sedikit terbiasa dengan buruh pelabuhan, kami memiliki beberapa hal lagi untuk dipelajari, jadi saya akan

00:08:34.390 --> 00:08:35.670
melihat Anda di video berikutnya.

00:08:35.870 --> 00:08:36.120
Buh-Bye.