WEBVTT

00:00:01.410 --> 00:00:02.310
Selamat datang kembali.

00:00:02.610 --> 00:00:07.730
Kami telah mempelajari beberapa perintah buruh pelabuhan dan cara membuat pertempuran udara.

00:00:08.220 --> 00:00:10.610
Tetapi ada beberapa hal yang ingin kita lakukan.

00:00:10.620 --> 00:00:17.700
Sebagai contoh, kami memiliki versi simpul kami, tetapi idealnya kami dapat menjalankan API otak pintar kami dalam

00:00:17.760 --> 00:00:18.760
wadah ini.

00:00:18.930 --> 00:00:20.360
Bagaimana kita bisa melakukan itu.

00:00:20.760 --> 00:00:24.090
Nah di video ini mari kita atasi itu.

00:00:24.260 --> 00:00:27.550
Izinkan saya memperkenalkan beberapa perintah buruh pelabuhan yang dapat kami gunakan.

00:00:27.560 --> 00:00:32.400
Yang pertama adalah direktori kerja atau instruksi pekerja.

00:00:32.540 --> 00:00:36.910
Dan ini mengatakan bahwa ini adalah direktori dalam wadah yang ingin kita kerjakan.

00:00:37.010 --> 00:00:44.800
Dan saya hanya akan membuat yang mengatakan aplikasi atau API otak cerdas logistik.

00:00:45.750 --> 00:00:47.790
Dan itu adalah direktori yang berfungsi.

00:00:47.790 --> 00:00:54.400
Jadi lain kali kita benar-benar pergi ke belakang wadah kita akan menemukan diri kita di sini

00:00:55.490 --> 00:01:04.100
Yang berikutnya yang kita miliki ingin kita gunakan adalah sesuatu seperti salin dalam salinan karena namanya menyarankan salinan apa

00:01:04.100 --> 00:01:10.190
pun yang kita inginkan dari direktori kita saat ini ke dalam wadah.

00:01:10.190 --> 00:01:14.420
Dalam kasus kami, ini adalah direktori root kami sehingga kami dapat mengatakan bahwa kami ingin

00:01:17.080 --> 00:01:17.860
menyalin semuanya.

00:01:18.370 --> 00:01:19.670
Dan direktori root ini.

00:01:19.750 --> 00:01:24.470
Dan di mana kita ingin memasukkannya ke dalam wadah kita.

00:01:24.550 --> 00:01:28.580
Dalam kasus kami, kami ingin meletakkannya di direktori kerja kami sehingga kami bisa tetap seperti itu.

00:01:28.930 --> 00:01:33.360
Dan omong-omong di sini saya bisa melakukan sesuatu seperti Jika saya

00:01:35.520 --> 00:01:41.670
hanya ingin menyalin paket file Jaison paket saya bisa melakukannya juga karena itu ada di direktori root.

00:01:41.740 --> 00:01:44.890
Sebelumnya kami ingin menyalin semuanya.

00:01:44.900 --> 00:01:46.070
Ini dia.

00:01:46.130 --> 00:01:53.840
Dan kemudian perintah terakhir yang akan saya ajarkan adalah menjalankan dan menjalankan hanya mengatakan apa yang harus kita lakukan di sini dan

00:01:54.440 --> 00:01:57.660
jenis perintah apa yang harus kita jalankan dalam wadah.

00:01:58.010 --> 00:02:03.210
Dan kami ingin menjalankan instalasi NPM karena kami telah membuat direktori yang berfungsi.

00:02:03.300 --> 00:02:08.410
Kami telah menyalin semua file ini dan kemudian kami ingin menjalankan NPM install.

00:02:08.420 --> 00:02:15.750
Jenis seperti apa yang kita lakukan ketika kita mendapatkan kloning ke desktop proyek kita dan kemudian jalankan NPM install.

00:02:15.890 --> 00:02:17.080
Itu hal yang persis sama.

00:02:18.080 --> 00:02:20.980
Dan Anda dapat menjalankan banyak perintah di sini.

00:02:20.990 --> 00:02:27.540
Sekarang Anda mungkin berpikir Apa perbedaan antara menjalankan dan perintah sekarang dijalankan adalah apa yang kita sebut gambar.

00:02:27.600 --> 00:02:28.330
Langkah.

00:02:28.460 --> 00:02:33.860
Keadaan wadah setelah menjalankan perintah akan dilakukan ke dermaga atau gambar.

00:02:33.860 --> 00:02:42.600
Jadi file Daco dapat menjalankan banyak langkah yang berjalan di atas satu sama lain untuk membangun gambar yang kita inginkan.

00:02:42.660 --> 00:02:49.540
Sekarang perintah di sisi lain adalah sesuatu yang secara default digunakan saat Anda menjalankan build image.

00:02:49.620 --> 00:02:56.690
Jadi dermaga atau jatuh hanya dapat memiliki satu komentar dan itu biasanya datang pada akhir musim gugur.

00:02:56.730 --> 00:03:00.370
Jadi mari kita periksa dan lihat apa yang terjadi jika saya menjalankan perintah ini sekarang.

00:03:00.570 --> 00:03:06.400
Jika saya masuk ke terminal saya dan sekali lagi mari kita buat ini sedikit lebih besar.

00:03:06.550 --> 00:03:17.120
Dan sekali lagi buruh pelabuhan Iran membangun super kami yang luar biasa.

00:03:17.130 --> 00:03:17.530
Baiklah.

00:03:17.550 --> 00:03:18.840
Anda lihat ada lebih banyak langkah.

00:03:18.840 --> 00:03:21.700
Sekarang menjalankan instalasi NPM.

00:03:21.780 --> 00:03:24.180
Kami memiliki sedikit peringatan tetapi saya pikir itu harus baik-baik saja.

00:03:24.180 --> 00:03:33.240
Dan akhirnya kami menjalankan perintah lima langkah dan sepertinya berhasil dibangun sekarang.

00:03:33.270 --> 00:03:36.500
Mari kita benar-benar masuk ke wadah ini dan melihat apa yang terjadi.

00:03:36.570 --> 00:03:46.360
Kami ingin menghapus ini dan mengatakan buruh pelabuhan menjalankan lagi Highty dan kemudian wadah super luar biasa beroperasi seperti ini

00:03:49.210 --> 00:03:56.510
direktori kerja kami adalah sumber pengguna API otak cerdas yang baru saja kami tetapkan.

00:03:56.550 --> 00:04:05.160
Dan jika saya lakukan tahun lalu betapa kerennya kita memiliki semua file dari komputer di wadah ini.

00:04:05.160 --> 00:04:07.340
Dan kami juga menjalankan NPM install.

00:04:07.440 --> 00:04:13.450
Jadi secara teoritis jika saya berlari dan mulai di sini betapa

00:04:16.480 --> 00:04:18.120
kerennya itu.

00:04:18.160 --> 00:04:23.000
Kami memiliki server kami berjalan pada wadah sekarang di wadah buruh pelabuhan.

00:04:23.020 --> 00:04:25.430
Aplikasi sedang berjalan di port 3000.

00:04:25.790 --> 00:04:26.010
BAIK.

00:04:26.020 --> 00:04:28.060
Jadi mari kita periksa.

00:04:28.090 --> 00:04:34.530
Saya membuka tab baru dan mari kita lakukan localhost tiga ribu.

00:04:34.980 --> 00:04:37.040
Situs dapat dihubungi.

00:04:37.350 --> 00:04:41.670
Dan itu karena localhost merujuk ke komputer kita.

00:04:42.000 --> 00:04:48.390
Tetapi jika Anda ingat tentang diskusi kami semua wadah adalah wadah hal yang benar-benar terpisah berjalan

00:04:48.390 --> 00:04:49.210
sendiri.

00:04:49.530 --> 00:04:54.150
Dan komputer kita tidak benar-benar memiliki pengetahuan tentang wadah itu.

00:04:54.770 --> 00:04:56.190
Dan itu masalahnya.

00:04:56.210 --> 00:05:01.580
Dan ini adalah sesuatu yang membuat banyak orang terjebak ketika kami memiliki sebuah

00:05:01.580 --> 00:05:10.260
wadah, biarkan aku keluar dari sini ketika kami memiliki sebuah wadah, wadah itu tidak benar-benar tahu tentang mesin itu. Kita harus

00:05:10.260 --> 00:05:13.770
benar-benar memberitahukannya ke mana harus membuka pelabuhan. .

00:05:13.770 --> 00:05:19.480
Anda melihat dunia luar yang komputer saya tidak dapat terhubung ke wadah secara default.

00:05:19.490 --> 00:05:25.320
Kita harus benar-benar memberi tahu kontainer apa yang harus diekspos dan kita menyebut port binding ini dan kita akan menggunakan teknik

00:05:25.320 --> 00:05:27.290
yang disebut port forwarding untuk melakukan ini.

00:05:27.330 --> 00:05:29.690
Dan itu terdengar lebih rumit dari itu.

00:05:29.730 --> 00:05:37.320
Yang perlu kita lakukan adalah dalam perintah kita, berikan parameter P dash yang berarti port dan berikan itu

00:05:37.320 --> 00:05:44.220
yang kita inginkan port tiga ribu pada wadah kita dan kita akan port 3000 pada host

00:05:44.220 --> 00:05:45.530
pada mesin.

00:05:45.840 --> 00:05:57.530
Jadi jika saya menjalankan ini OK kita sudah pergi ke wadah saya berlari NPM mulai aplikasi kami berjalan pada port

00:05:57.530 --> 00:06:08.040
3000 dan sekarang jika kita kembali referensi R8 database mereka tidak didefinisikan dan itu karena jika kita

00:06:08.160 --> 00:06:19.170
pergi ke server kita cerdik kita miliki di sini di Dapatkan permintaan basis data pengguna yang sebenarnya tidak benar.

00:06:19.170 --> 00:06:23.070
Kami memiliki D-B sekarang kami tidak pernah menggunakan database tetapi sebenarnya berfungsi.

00:06:23.250 --> 00:06:25.700
Jadi mari kita ubah ke.

00:06:25.980 --> 00:06:27.990
Bekerja.

00:06:28.970 --> 00:06:38.080
Kami ingin menyimpan dan mari menyegarkan kembali dan bagian yang sulit adalah kita harus menjalankan ini lagi.

00:06:38.090 --> 00:06:42.050
Biarkan saya menutup ini dan menjalankan start NPM.

00:06:42.130 --> 00:06:53.180
Mari kita kembali dan menyegarkan dan Anda melihat bagaimana itu sebenarnya tidak berfungsi sekarang dan itu karena dan kita benar-benar

00:06:58.870 --> 00:07:02.010
harus mari kita tutup ini.

00:07:02.050 --> 00:07:06.990
Kita akan keluar dan membangun kembali gambar kita mulai menyalin

00:07:10.040 --> 00:07:13.210
file yang kita jalankan melalui langkah-langkah.

00:07:14.180 --> 00:07:18.820
Kemudian akhirnya jalankan wadah kami dan jika kami menggunakan NPM, mulailah sekarang.

00:07:20.700 --> 00:07:23.220
Kembali dan segarkan.

00:07:23.410 --> 00:07:25.080
Bekerja.

00:07:25.280 --> 00:07:28.090
Betapa menyenangkan rasanya itu.

00:07:28.100 --> 00:07:33.030
Kami baru saja secara resmi membuat wadah Dharker untuk server API kami.

00:07:33.350 --> 00:07:41.120
Jadi sekarang yang perlu kita lakukan adalah memberikan folder ini dengan dokumen atau file di mana saja dan

00:07:41.150 --> 00:07:46.830
selama mereka memiliki dokter, kita cukup menjalankan ini pada mesin yang kita inginkan.

00:07:46.860 --> 00:07:50.540
Sangat keren tapi ada masalah sekarang.

00:07:51.640 --> 00:07:53.930
Bagaimana dengan basis data ini.

00:07:54.040 --> 00:07:55.300
Apa yang kita lakukan dengan itu.

00:07:55.300 --> 00:07:58.340
Apa yang kita lakukan dengan postkrip untuk itu.

00:07:58.450 --> 00:08:00.690
Anda harus menunggu video berikutnya.

00:08:00.970 --> 00:08:01.890
Saya akan lihat yang itu.